spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/spring-cloud-auth
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 5000
  context-path: /uaa
security:
  oauth2:
    resource:
      filter-order: 3
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka